### ISSUE TITLE
Antivirus detection

### ISSUE THREAD

**Issue by jhemp** [quarkslab/irma-probe#1]
Issue 1: 
Antivirus was not found (i.e. folder not in PATH) -> celery starts with default queue. Frontend recognizes it and schedules a scan -> timeout for scan

Issue 2:
Got not detected:
McAfee Antivirus 2014

**Comment by ch0k0bn** [comment]
when installing an antivirus you could check if it will be discovered by IRMA by checking the plugin source code https://github.com/quarkslab/irma-probe/blob/master/modules/antivirus/mcafee/vscl.py#L121 For Mcafee on windows it looks for a scan.exe in c:\VSCL for example
