### ISSUE TITLE
Need to get Virus definition version number in scan result along with antivirus product version

### ISSUE THREAD

**Issue by rjbhide** [quarkslab/irma-probe#52]
Currently we get results like this,
{"status": 0, "name": "McAfee VirusScan Command Line scanner", "results": null, "version": "6.0.4.564", "duration": 12.68, "type": "antivirus"}

It's great that we get AV product version "6.0.4.564". But the thing is, AV product version doesn't update automatically but virus definitions does (& happen almost daily). 
It will be great if you can include Virus definition information along with (or instead of ) AV product version.

**Comment by ch0k0bn** [comment]
In fact, we collect more information on antivirus database than that but they are filtered before display. We collect all signatures files hash value and they are stored in db. You could see them by adding "formatted=no" to the api call.
e.g: http://<irma_server>/api/v1/scans/<scanid>/results/0?formatted=no
But you are right we dont have the virus definition version. Something to add.
