### ISSUE TITLE
Unable to see probes in frontend

### ISSUE THREAD

**Issue by andrewjones216** [quarkslab/irma-probe#54]
Hi all,

My environment is as follows:
 - Debian 8.0.0 VM with Brain and Frontend installed (as per the manual instructions)
 - Debian 8.0.0 VM with a number of Static Linux Probes installed (as per manual instructions)
 - Debian 8.0.0 VM with a number of Linux AV Probes installed (as per manual instructions)
 - Windows 7 Pro VM with a number of Windows AV Probes installed (as per manual instructions)

All post-install checks return expected results and no errors are being reported in any logs that I can find.
Network wise the VMs can all ping hostnames and IP addresses of eachother, there are no firewalls and IPtables has not been configured with any rules on the Debian boxes. 

When running up the Frontend, no probes show. Is anyone able to help with this issue and suggest ways forward?

Kind Regards
Andrew

**Comment by kamino** [comment]
@andrewjones216, does the celery logs on the probes and the frontend show that they are connected to the brain ?

a thing I may think of for your issue is collision on hostnames, but I assume that you have different hostnames for your different virtual machines ?

If it is still not solved, come on IRC and leave me a message. We can discuss more about your issue and try to find a solution quickly.

**Comment by andrewjones216** [comment]
Hi kamino,

The celery logs showed a discrepancy in time between the brain and one of the probes. Once I'd fixed that the probes are showing in the frontend. 

Part2:
I have two different hosts for Probes connected at the moment:
IRMA-Windows: Kaspersky/ Sophos/ Avira and GDATA
IRMA-Linux: ClamAV

What I see in the interface is "ClamAV/ GDATA/ Kaspersky/ Sophos and brain".
When pressing 'scan for malwares' I get a red bar at the top of the page that says "API error". Could this error be to do with the mystery probe 'brain'?


Cheers

**Comment by kamino** [comment]
@andrewjones216 : the ``brain`` should not appear in the probe list. Can you double check the rabbitmq vhosts you configured ? In the expected configuration, the brain should not be there.

**Comment by andrewjones216** [comment]
![23-06-2015 16-52-18](https://cloud.githubusercontent.com/assets/12948449/8310514/55be9682-19c8-11e5-9bf0-eac785935843.png)

No brain listed as a vhost in rabbitmq.
Cheers
Andrew

**Comment by ch0k0bn** [comment]
brain is a queue on "mqbrain" vhost, available probes list is the queues list on "mqprobe" vhost. Check your brain and frontend config files to see if the "brain" queue is correctly set on the "mqbrain" vhost (check here https://github.com/quarkslab/irma-brain/blob/master/config/brain.ini#L4 and here https://github.com/quarkslab/irma-frontend/blob/master/config/frontend.ini#L22 /opt/irma/irma-frontend/config/frontend.ini and /opt/irma/irma-brain/config/brain.ini).

**Comment by andrewjones216** [comment]
That's worked well thank you, for some reason I had "brain" as the username for mqprobe in the brain.ini file. 
New territory for me having never used celery, rabbitmq or even Debian! IRMA looks like a good fit for what we need.

I do still get the "API error" red bar after clicking "Scan for malwares"?

Cheers
Andrew

**Comment by guillaumededrie** [comment]
Hi @andrewjones216,
Can you give us logs from your server? They should be located at `/var/log/supervisor/frontend_api.log`.

Regards,

**Comment by andrewjones216** [comment]
Hi @guillaumededrie,
I've checked on my server and I do not have a folder "supervisor" located in /var/log/...

![31-07-2015 08-46-27](https://cloud.githubusercontent.com/assets/12948449/9002884/d712bc26-3760-11e5-800e-f60b0e5c0bf6.png)

Cheers
Andrew

**Comment by guillaumededrie** [comment]
Hum, your are using the new Debian 8.1 version, is that right?

**Comment by andrewjones216** [comment]
I'm using Debian 8.0 on all the VM's

**Comment by ch0k0bn** [comment]
feel free to re-open an issue if you are still stuck with this problem.
