### ISSUE TITLE
Virus Blokada interface script consider suspect binaries as error

### ISSUE THREAD

**Issue by p-col** [quarkslab/irma-probe#56]
The Virus Blokada's script interfacing with Virus Blokada does not consider suspect binaries as infected (return value == 6 from the tool). Irma consider therefore that 6 is an error and result into a -1 status in the json report from the API.
https://github.com/quarkslab/irma-probe/blob/8a3971c61db15ee66126d9b7dc219eac124e0ed8/modules/antivirus/virusblokada/virusblokada.py#L51
In order to solve this, just add 6 in the list:
- self._scan_retcodes[self.ScanResult.INFECTED] = lambda x: x in [7]
+ self._scan_retcodes[self.ScanResult.INFECTED] = lambda x: x in [6, 7]

**Comment by kamino** [comment]
@p-col can you do a pull request against the testing branch ? I can do it myself, but I want you have the credits for your findings :) thanks in advance !

**Comment by p-col** [comment]
Here it is: https://github.com/quarkslab/irma-probe/pull/57 =)

**Comment by guillaumededrie** [comment]
Thank you @p-col, I close the issue as your PR resolve it. Don't hesitate to re-open it if not.

Regards,
